import Head from "next/head";

export default function Design() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="font-bold">H1 Headline / Bold</h1>
        <h1>H1 Headline / Regular</h1>
        <p className="text-2xl font-Raleway font-bold">subtitle / Bold</p>
        <p className="text-2xl font-Raleway">subtitle / Regular</p>
        <h2>H2 headline</h2>
        <h3>H3 headline</h3>
        <h4>H4 headline</h4>
        <h5>h5 headline</h5>
        <p className="font-Raleway text-base font-bold">Main / Bold</p>
        <p className="font-Raleway text-base">Main / Regular</p>
        <p className="text-sm font-Montserrat">MENU</p>
        <p className="text-xs font-Montserrat leading-[14.63px]">Additional</p>
        <p className="text-xs font-Raleway font-bold">Small / Bold</p>
        <p className="text-xs font-Raleway">Small / Regular</p>
      </main>
    </>
  );
}
