import Head from "next/head";
import classes from "./font.module.scss";

export default function fome() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.test}>
        <h1 className={classes.h1_bold}>H1 Headline / Bold</h1>
        <h1 className={classes.h1_regular}>H1 Headline / Regular</h1>
        <p className={classes.subtitle_bold}>subtitle / Bold</p>
        <p className={classes.subtitle_regular}>subtitle / Regular</p>
        <h2>H2 headline</h2>
        <h3>H3 headline</h3>
        <h4>H4 headline</h4>
        <h5>h5 headline</h5>
        <p className={classes.main_bold}>Main / Bold</p>
        <p className={classes.main_regular}>Main / Regular</p>
        <p className={classes.menu}>MENU</p>
        <p className={classes.additional}>Additional</p>
        <p className={classes.small_bold}>Small / Bold</p>
        <p className={classes.small_regular}>Small / Regular</p>
      </main>
    </>
  );
}