name: Auto Merge to Production and Deploy

on:
  schedule:
    # This runs at 12pm every second Thursday
    - cron: '0 12 * * 4'

jobs:
  merge_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      # It is very important to use V1 because the other version's checkout only fetches the last commit by default.
      # So you don't have enough past commits to find a common ancestor if you are not using V1.
      # It will meet an error with fatal: refusing to merge unrelated histories.
      # Or there is another way using: "with: fetch-depth: x" to set more fetch-depth
      uses: actions/checkout@v1

    - name: Automatic Merge
      uses: robotology/gh-action-nightly-merge@v1.4.0
      with:
        stable_branch: "main"
        development_branch: "production"
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
